#!/bin/bash

echo "Enter any number"
read n

if [[ ( $n -eq 15 || $n  -eq 45 ) ]]  # here in place of eq option we also use double equal sign
then
echo "You won the game"
else
echo "You lost the game"
fi
