#!/bin/bash

echo "Enter username"
read username
echo "Enter password"
read password

if [[ ( $username == "admin" && $password == "needle" ) ]];   # double big bracket is used to handle complex condition
then
echo "valid user"
else
echo "invalid user"
fi
